# Generated by Django 2.1.3 on 2018-12-06 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Danhsach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Specialized', models.CharField(max_length=300)),
                ('Level', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Thongtin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ngaysinh', models.CharField(max_length=250)),
                ('Sothich', models.CharField(max_length=250)),
                ('danhsach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Danhsach')),
            ],
        ),
    ]
