# Generated by Django 2.1.3 on 2018-12-06 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Danhsach_CoTruong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Specialized', models.CharField(max_length=300)),
                ('Level', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='thongtin',
            name='danhsach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Danhsach_CoTruong'),
        ),
        migrations.DeleteModel(
            name='Danhsach',
        ),
    ]
